version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules # do not map to the external node_modules folder
            - .:/app # map the current folder outside the container to the /app folder inside
        stdin_open: true # fix for React scripts
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true
        command: ["npm", "run", "test"]
